version: '2'
services:
    runningcoincs-app:
        image: runningcoincs
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://runningcoincs-mysql:3306/runningcoincs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    runningcoincs-mysql:
        extends:
            file: mysql.yml
            service: runningcoincs-mysql
